version: '3.8'
services:
  crawler:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
